### ISSUE TITLE
bookdown left side panel width

### ISSUE THREAD

**Issue by lucashertzog** [cardat/air-health-sws-r-targets-technique-tweaking-tinkering#3]
@ivanhanigan in repo/docs/libs/gitbook-2.6.7/css/style.css

.book .book-summary{position:absolute;top:0;left:-300px;bottom:0;z-index:1;width:700px;color:#364149;background:#fafafa;border-right:1px solid rgba(0,0,0,.07);-webkit-transition:left 250ms ease;-moz-transition:left 250ms ease;-o-transition:left 250ms ease;transition:left 250ms ease}

Standard width is 300px. In this example, changed to 700px.

**Comment by ivanhanigan** [comment]
@lucashertzog Hi Lucas, Can you describe more about what Karthik and I need to change to get this to work?
Is this style.css file somewhere in the same folder or elsewhere on the computer?

**Comment by lucashertzog** [comment]
the data inventory has a dedicated style css that can be found here:

cardat.github.com/data_inventory/libs/gitbook-2.6.7/css/style.css

the size of the left panel, in pixels, can be edit in this line:

.book .book-summary{position:absolute;top:0;left:-300px;bottom:0;z-index:1;width:500px;color:#364149;background:#fafafa;border-right:1px solid rgba(0,0,0,.07);-webkit-transition:left 250ms ease;-moz-transition:left 250ms ease;-o-transition:left 250ms ease;transition:left 250ms ease}

in this case, width is set to 500px. other features might be edited here as well (font colour, background colour etc)
