### ISSUE TITLE
TweTin as a prefix?

### ISSUE THREAD

**Issue by lucashertzog** [cardat/air-health-sws-r-targets-technique-tweaking-tinkering#4]
@ivanhanigan perhaps we can create a TweTin prefix for general technique tweaking and tinkering? This will be a repo with information such as the one I tagged you on previously (left panel bookdown width), general discussion about tidy vs tiny etc.

**Comment by ivanhanigan** [comment]
@lucashertzog this is a good prefix for issues. thanks
